name: Release

on:
  push:
    tags:
      - "v*" # Run workflow on version tags, e.g. v1.2.0.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: # new line
      id-token: write # new line
      contents: write # new line
      attestations: write # new line

    steps:
      - uses: actions/checkout@v6

      - uses: grafana/plugin-actions/build-plugin@build-plugin/v1.2.0
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          go-version: "1.26.4"
          attestation: true
